### ISSUE TITLE
Time multiple versions

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/travis_qmake_gcc_cpp11#1]
# 1: apt-get

```
sudo: require
language: cpp
compiler: gcc

before_install:
  # C++11
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp11
```

```
# Project files
SOURCES += main.cpp

# Compile with high warning levels, a warning is an error
QMAKE_CXXFLAGS += -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Weffc++ -Werror

# C++11
CONFIG += c++11
QMAKE_CXX = g++-5
QMAKE_LINK = g++-5
QMAKE_CC = gcc-5
QMAKE_CXXFLAGS += -std=c++11
```

# 2: addons

Gist from https://gist.github.com/cotsog/3ce84675af0d74438d91

```
sudo: required
script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

script: 
  - qmake
  - make
  - ./travis_qmake_gcc_cpp11
```

```
# Project files
SOURCES += main.cpp

# Compile with high warning levels, a warning is an error
QMAKE_CXXFLAGS += -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Weffc++ -Werror

# C++11
CONFIG += c++11
QMAKE_CXX = g++-5
QMAKE_LINK = g++-5
QMAKE_CC = gcc-5
QMAKE_CXXFLAGS += -std=c++11
```
